trigger:
  - main

pool:
  name: Default

steps:
  - script: |
      docker run --rm \
        -e "INPUT_SERVICE_ACCOUNT_KEY=$(CJ_SERVICE_ACCOUNT_KEY)" \
        -e "INPUT_TEST_ID=$(CJ_TEST_ID)" \
        foreai/cj-action:latest
    displayName: 'Run fore ai Test'
    env:
      CJ_SERVICE_ACCOUNT_KEY: $(CJ_SERVICE_ACCOUNT_KEY)
